// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmdafdmgilpcyrhlrfpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZGFmZG1naWxwY3lyaGxyZnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mjk4MTEsImV4cCI6MjA2NDEwNTgxMX0.66_mzCV20Wfn_p3quIIxnVTbYMvc_ElE3VBxc1lKW8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);